CREATE table if not exists categories(
    ID int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME varchar(255)
);

CREATE table if not exists users_categories(
    USER_ID int,
    CATEGORY_ID int
);

 ALTER TABLE users_categories
    ADD FOREIGN KEY (USER_ID) 
    REFERENCES users(ID);
    
 ALTER TABLE users_categories
    ADD FOREIGN KEY (CATEGORY_ID) 
    REFERENCES categories(ID);